id: 3be9944aabba4fc5a00b8af8e1543007
title: Toh_151-The_Questions_of_Pratibhanamati-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-057-010
  eft-text-version: 1.1.9 2021
